<?php
    namespace App\Models;

    use Bearlovescode\Laravel\Models\Model;
    use Illuminate\Support\Carbon;

    class Tweet extends Model {
        protected $_vars = [
            'id' => '',
            'snowflake_id' => '',
            'lang' => '',
            'body' => '',
            'author' => '',
            'source' => '',
            'favorited' => 0,
            'retweeted' => 0,
            'truncated' => 0,
            'created_at' => '',
            'updated_at' => ''
        ];


        public function hydrate(mixed $data = null): void
        {
            // dates.
            if (isset($data->created_at))
            {
                $this->created_at = new Carbon($data->created_at);
                unset($data->created_at);
            }

            if (isset($data->updated_at))
            {
                $this->updated_at = new Carbon($data->updated_at);
                unset($data->updated_at);
            }



            parent::hydrate($data); // TODO: Change the autogenerated stub
        }


    }
